#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gabbi
Version  : 1.45.0
Release  : 67
URL      : https://files.pythonhosted.org/packages/03/a7/fb0c14b9b34b7c10a405ce3021bfc9130d06f636dd16611b52ea4e3fd713/gabbi-1.45.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/03/a7/fb0c14b9b34b7c10a405ce3021bfc9130d06f636dd16611b52ea4e3fd713/gabbi-1.45.0.tar.gz
Summary  : Declarative HTTP testing library
Group    : Development/Tools
License  : Apache-2.0
Requires: gabbi-bin = %{version}-%{release}
Requires: gabbi-license = %{version}-%{release}
Requires: gabbi-python = %{version}-%{release}
Requires: gabbi-python3 = %{version}-%{release}
Requires: PyYAML
Requires: colorama
Requires: jsonpath-rw-ext
Requires: pbr
Requires: six
Requires: testtools
Requires: urllib3
Requires: wsgi_intercept
BuildRequires : Babel-python
BuildRequires : Jinja2
BuildRequires : PyYAML
BuildRequires : Pygments
BuildRequires : Sphinx-python
BuildRequires : buildreq-distutils3
BuildRequires : coverage-python
BuildRequires : docutils-python
BuildRequires : extras
BuildRequires : fixtures-python
BuildRequires : flake8-python
BuildRequires : gabbi
BuildRequires : hacking
BuildRequires : httplib2
BuildRequires : linecache2-python
BuildRequires : markupsafe-python
BuildRequires : mccabe-python
BuildRequires : pbr
BuildRequires : pep8
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : ply-python
BuildRequires : py-python
BuildRequires : pyflakes-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mimeparse
BuildRequires : python-mock
BuildRequires : python-subunit
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : testrepository
BuildRequires : testresources
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : tox
BuildRequires : traceback2
BuildRequires : unittest2
BuildRequires : virtualenv
BuildRequires : wsgi_intercept
BuildRequires : wsgiref
Patch1: req.patch

%description
Some of the tests in this collection will attempt to connect to
google over the internet to validate some behaviors using real
socket connections. If this is not desirable (for example behind
firewalls or in packaging situations) set GABBI_SKIP_NETWORK to
true in the environment running the tests.

%package bin
Summary: bin components for the gabbi package.
Group: Binaries
Requires: gabbi-license = %{version}-%{release}

%description bin
bin components for the gabbi package.


%package license
Summary: license components for the gabbi package.
Group: Default

%description license
license components for the gabbi package.


%package python
Summary: python components for the gabbi package.
Group: Default
Requires: gabbi-python3 = %{version}-%{release}

%description python
python components for the gabbi package.


%package python3
Summary: python3 components for the gabbi package.
Group: Default
Requires: python3-core

%description python3
python3 components for the gabbi package.


%prep
%setup -q -n gabbi-1.45.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552575082
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test --verbose py2 ||:
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gabbi
cp LICENSE %{buildroot}/usr/share/package-licenses/gabbi/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gabbi-run

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gabbi/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
